#!/usr/bin/env bash
set -euo pipefail

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
nix-shell -E "with import $ROOT/../nix {}; mkShell { buildInputs = [ (nixos {}).nixos-rebuild ]; }" --run "nixos-rebuild $*"
