#!/usr/bin/env bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
nix-shell -E "with import $ROOT/../nix {}; stdenv.mkDerivation { name = \"foo\"; buildInputs = [ (nixos {}).nixos-rebuild ]; }" --run "nixos-rebuild $*"
